### Local Configuration Variables ###
HS_PATH: /home/hydro/hydroshare
HOST_SSL_DIR: /home/hydro/hydroshare/nginx/cert-files
HS_DATABASE: pg.deploy.sql
HS_LOG_FILES: /home/hydro/hydroshare/log
HS_SERVICE_UID: 214401701
HS_SERVICE_GID: 214401702

### Deployment Options ###
USE_NGINX: true
USE_SSL: true
USE_SECURITY: false
USE_HTTP_AUTH: false

### nginx Configuration Variables ###
FQDN_OR_IP: dev-hs-3.cuahsi.org
NGINX_DIR: /home/hydro/hydroshare/nginx

### SSL Configuration Variables ###
SSL_CERT_DIR: /home/hydro/hydroshare/nginx/cert-files
SSL_CERT_FILE: cuahsi.crt
SSL_KEY_FILE: cuahsi.key

## Mount point in host operating system (outside docker)
#### This is mounted from here into the Nginx container
IRODS_LOCAL_MOUNT: /irods

#### Mount points inside docker Nginx container
#### These give Nginx direct access to iRODS vaults
#### All ROOTs must be children of DOCKER_MAP ###
IRODS_DOCKER_MAP: /irods
IRODS_DATA_ROOT: /irods/data/
IRODS_USER_ROOT: /irods/user/
IRODS_CACHE_ROOT: /irods/cache/

#### Nginx worker process must be able to read iRODS files.
SENDFILE_IRODS_USER: irods
SENDFILE_IRODS_GROUP: irods
SENDFILE_IRODS_USER_ID: 214401721
SENDFILE_IRODS_GROUP_ID: 214400513

#### URIs in Nginx that activate reverse proxy service
#### These must agree with URIs in local_settings.py
IRODS_DATA_URI: irods-data
IRODS_USER_URI: irods-user
IRODS_CACHE_URI: irods-cache

### REQUIRES BLANK LINE AFTER LAST VARIABLE DEFINITION ###

